apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orchestrateops.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "orchestrateops.name" . }}
  template:
    metadata:
      labels:
        # app: {{ include "orchestrateops.name" . }}
        app: orchestrateops
        env: production # Exemplo de outra tag (opcional)
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/data  # Monta o diretório persistente para o banco de dados
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-sqlite-pvc  # Nome do PVC com o prefixo da release
