apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "orchestrateops.fullname" . }}-limit-range
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "orchestrateops.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limits.default.cpu | quote }}
        memory: {{ .Values.limits.default.memory | quote }}
      defaultRequest:
        cpu: {{ .Values.limits.defaultRequest.cpu | quote }}
        memory: {{ .Values.limits.defaultRequest.memory | quote }}
