apiVersion: v1
kind: PersistentVolume
metadata:
  name: orchestrateops-pv
  labels:
    app: orchestrateops
spec:
  capacity:
    storage: {{ .Values.persistence.size | default "5mi" }}
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteMany" }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/orchestrateops"  # Diretório onde o PV será montado no nó
