apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "orchestrateops.fullname" . }}-pv
  labels:
    app: {{ include "orchestrateops.name" . }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    environment: {{ .Values.environment | default "production" }}
spec:
  capacity:
    # Comente/Descomente alternadamente as duas linhas seguintes (storage: ) para teste de capacidade de armazenamento.
    storage: {{ .Values.persistence.size | default "10Mi" }}
    # storage: "100Mi"
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass | default "manual-storage" }}
  hostPath:
    path: {{ .Values.persistence.hostPath | default "/data/orchestrateops" }}
