apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "orchestrateops.fullname" . }}-resource-quota
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "orchestrateops.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requests.cpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requests.memory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limits.cpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limits.memory | quote }}
