apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrateops.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "orchestrateops.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
  selector:
    app: {{ include "orchestrateops.name" . }}
